name: publish

on:
  workflow_dispatch:

env:
  VERSION: "0.1.${{ github.run_number }}"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./backend
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ env.VERSION }}
      
      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./frontend
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ env.VERSION }}